return {
  Arrow_closed = "",
  Arrow_open = "",
  Corner = "└",
  Edge = "│",
  Item = "│",
  Bottom = "─",
  None = " ",
  Bookmark = "",
  Modified = "●",
  File = "",
  Files = "",
  Folder = "",
  OpenFolder = "",
  EmptyFolder = "",
  OpenEmptyFolder = "",
  Symlink = "",
  SymlinkArrow = " ➛ ",
  SymlinkFolder = "",
  SymlinkFolder_open = "",
}
