return {
  statusline = {
    Added = " ",
    Modified = " ",
    Removed = " ",
  },
  signcolumn = {
    Add = "┃",
    Change = "┃",
    Delete = "",
    Topdelete = "",
    Changedelete = "",
    Untracked = "┃",
  },
  file_explorer = {
    Add = " ",
    Mod = " ",
    Remove = " ",
    Ignore = " ",
    Rename = " ",
    Diff = " ",
    Repo = " ",
    Octoface = " ",
    Branch = "",
    Unstaged = "",
    Staged = "S",
    Unmerged = "",
    Renamed = "➜",
    Untracked = "U",
    Deleted = "",
    Ignored = "",
  },
}
