local i = require("user.resources.kind_icons")

for key, value in pairs(i) do
  i[key] = value:match("^%s*(.-)%s*$")
end

M = {
  attach_navic = false,
  create_autocmd = false,
  include_buftypes = { "" },
  exclude_filetypes = {
    "alpha",
    "dapui_scopes",
    "dapui_breakpoints",
    "dapui_stacks",
    "dapui_watches",
    "dap-repl",
    "dap-terminal",
    "dapui_console",
    "dashboard",
    "dirvish",
    "DressingInput",
    "fugitive",
    "help",
    "lazy",
    "lspinfo",
    "Man",
    "man",
    "mason",
    "Markdown",
    "netrw",
    "NvimTree",
    "packer",
    "spectre_panel",
    "startify",
    "toggleterm",
    "TelescopePrompt",
  },
  modifiers = {
    ---See: `:help filename-modifiers`
    dirname = ":~:.",
    basename = "",
  },
  show_dirname = true,
  show_basename = true,
  show_modified = true,
  modified = function(bufnr) return vim.bo[bufnr].modified end,
  show_navic = true,
  lead_custom_section = function() return "" end,
  custom_section = function() return "" end,
  theme = "auto",
  context_follow_icon_color = false,
  symbols = {
    modified = "●",
    ellipsis = "…",
    separator = "",
  },
  kinds = {
    File = i.File,
    Module = i.Module,
    Namespace = i.Namespace,
    Package = i.Package,
    Class = i.Class,
    Method = i.Method,
    Property = i.Property,
    Field = i.Field,
    Constructor = i.Constructor,
    Enum = i.Enum,
    Interface = i.Interface,
    Function = i.Function,
    Variable = i.Variable,
    Constant = i.Constant,
    String = i.String,
    Number = i.Number,
    Boolean = i.Boolean,
    Array = i.Array,
    Object = i.Object,
    Key = i.Key,
    Null = i.Null,
    EnumMember = i.EnumMember,
    Struct = i.Struct,
    Event = i.Event,
    Operator = i.Operator,
    TypeParameter = i.TypeParameter,
  },
}

return M
